# Generated by Django 2.1.5 on 2019-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('typething', models.TextField(choices=[('stk', 'stk'), ('l', 'l'), ('kg', 'kg'), ('ss', 'ss'), ('ts', 'ts')], max_length=3)),
            ],
        ),
    ]
